# Generated by Django 3.1.3 on 2021-09-26 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(default='default.jpg', null=True, upload_to='attachments')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(default='Enter the Brand Item Code and Quantity of your requirement', null=True)),
                ('brand', models.CharField(choices=[('abb', 'ABB'), ('legrand', 'LEGRAND'), ('phoenix mecano', 'PHEONIX MECANO'), ('eaton', 'EATON')], max_length=40)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Converted', 'Converted'), ('Failed', 'Failed')], max_length=10)),
            ],
        ),
    ]
