# Generated by Django 3.1.3 on 2021-09-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Converted', 'Converted'), ('Failed', 'Failed')], default='Open', max_length=10),
        ),
    ]
