# Generated by Django 3.1.3 on 2021-09-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0004_auto_20210926_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(default='null@noemail.com', max_length=254),
        ),
    ]
