# Generated by Django 3.1.3 on 2021-09-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0005_auto_20210926_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='attachment',
            field=models.FileField(default='default.jpg', null=True, upload_to='enquiry_attachments'),
        ),
    ]
