# Generated by Django 3.1.3 on 2022-01-09 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0007_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='address',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='email',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(default='No address', max_length=150),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=None, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone no must be entered in format: Up to 10 digits allowed.', regex='^\\ ?1?\\d{9,15}$')]),
        ),
    ]
