# Generated by Django 3.1.3 on 2022-01-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0008_auto_20220109_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='title',
            new_name='party',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='description',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='cust_type',
            field=models.CharField(choices=[('OEM', 'OEM'), ('Ex', 'Ex'), ('T', 'T'), ('En', 'En'), ('C', 'C'), ('A', 'A')], default='T', max_length=10),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='item_code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='brand',
            field=models.CharField(choices=[('abb', 'ABB'), ('legrand', 'LEGRAND'), ('phoenix mecano', 'PHEONIX MECANO'), ('eaton', 'EATON'), ('Bussmann', 'Bussmann')], default='Bussmann', max_length=40),
        ),
    ]
