# Generated by Django 3.1.3 on 2022-01-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0009_auto_20220109_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='media',
            field=models.CharField(choices=[('E', 'E'), ('W', 'W'), ('A', 'A')], default='E', max_length=10),
        ),
    ]
