# Generated by Django 3.1.3 on 2022-01-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0010_enquiry_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Converted', 'Converted'), ('Failed', 'Failed')], default='Open', max_length=10, null=True),
        ),
    ]
