# Generated by Django 3.1.3 on 2022-01-13 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0012_remove_enquiry_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
