# Generated by Django 3.1.3 on 2022-01-13 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0013_auto_20220113_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
