# Generated by Django 3.1.3 on 2022-01-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0015_auto_20220123_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='attachment',
            field=models.FileField(default='default.jpg', null=True, upload_to='enquiry_attachments'),
        ),
    ]
