# Generated by Django 3.1.3 on 2022-01-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0017_auto_20220129_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='attachment',
            field=models.FileField(default='default.jpg', null=True, upload_to='enquiry_attachments'),
        ),
    ]
