# Generated by Django 3.1.3 on 2022-01-29 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0018_auto_20220129_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='attachment',
        ),
    ]
