# Generated by Django 3.1.3 on 2022-01-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0019_remove_enquiry_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Quoted', 'Quoted'), ('Converted', 'Converted'), ('Failed', 'Failed')], default='Open', max_length=10, null=True),
        ),
    ]
